---
- name: Ensure Swarm Exist
  command: "docker swarm init --advertise-addr {{ advertise_addr or swarm_managers[0] }}"
  failed_when: false
  ignore_errors: yes

- name: Get Manager Token
  command: "docker swarm join-token manager -q"
  register: manager_token

- name: Get Worker Token
  command: "docker swarm join-token worker -q"
  register: worker_token

- name: Set Token
  set_fact:
    manager_addr: "{{ advertise_addr or swarm_managers[0] }}"
    manager_token: "{{ manager_token.stdout }}"
    worker_token: "{{ worker_token.stdout }}"